export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const OPEN_CREATE_POST_NAV = 'OPEN_CREATE_POST_NAV';
export const CLOSE_CREATE_POST_NAV = 'CLOSE_CREATE_POST_NAV';


export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_LOADING = 'CREATE_POST_LOADING';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
