export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const OPEN_CREATE_POST_NAV = 'OPEN_CREATE_POST_NAV';
export const CLOSE_CREATE_POST_NAV = 'CLOSE_CREATE_POST_NAV';


export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_LOADING = 'CREATE_POST_LOADING';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const GET_CONNECTIONS_BY_ID = 'GET_CONNECTIONS_BY_ID';
export const CONNECTIONS_LOADING = 'CONNECTIONS_LOADING';
export const GET_CONNECTIONS_BY_ID_ERROR = 'GET_CONNECTIONS_BY_ID_ERROR';

export const GET_USER_CONNECTIONS_BY_ID = 'GET_USER_CONNECTIONS_BY_ID';
export const USER_CONNECTIONS_LOADING = 'USER_CONNECTIONS_LOADING';
export const GET_USER_CONNECTIONS_BY_ID_ERROR = 'GET_USER_CONNECTIONS_BY_ID_ERROR';

export const CONNECTIONS_USER_LOADING = 'CONNECTIONS_USER_LOADING';
export const CONNECTIONS_USER_DETAILS = 'CONNECTIONS_USER_DETAILS';

export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS';
export const GET_ALL_REQUESTS_ERROR = 'GET_ALL_REQUESTS_ERROR';